### PR TITLE
versioning and vendor aep attributes

### PR DESCRIPTION
**Pull request by joshco**
A proposal for server protocol version advertisement
Also added some vendor attributes for AEP

### CODE REVIEW

**Comment by raysuelzer** [comment]
+1

**Comment by shaisachs** [comment]
Looks good to me.  FWIW, we would probably provide nearly-identical values for "vendor_name" and "product_name", e.g. "NGP VAN" or something, since we'd probably want to provide all of our resources (whether from NGP or from VAN) under a single AEP umbrella.  But I can see how that'd be useful in other scenarios.

**Comment by joshco** [comment]
Key Discussion from 3/26:
Should version be in header or AEP?

**Comment by alexisireland** [comment]
Looks good. We would likely have to consider the values we provide given we have 2 products that are completely separated and vastly different, technically. Happy to elaborate if there are questions.

**Pull request merged**
