### PR TITLE
share options proposal

### PR DESCRIPTION
**Pull request by j-ro**
Not finished yet, only on advocacy campaigns right now, but good for an initial look.

### CODE REVIEW

**Comment by kyle-rader** [comment]
@j-ro These kind of sharing options seem relative to our work at ActionSprout.  Could we get some more context for this proposal? (Maybe via email)  Amiel Martin and I have a meeting conflict with this Thursday's meeting.

**Comment by j-ro** [comment]
Hi @kyle-rader, basically the idea here is we're extending some attributes we had on one resource to others.

Currently we have the share page resource (https://github.com/opensupporter/osdi-docs/blob/gh-pages/share_pages.md). This resource represents standalone share pages which can be sharing any type of content. It has various fields to describe the language being shared, like the Facebook title, suggested tweet, etc....

The idea here is to extend some of those fields to other resources. In systems like ours, we don't have standalong share pages. Rather, share pages are attached to actions like petitions. So in our user interface you can make a petition and determine the share language you want to use all in one, and the thank you page after you sign a petition is the share buttons with that language. So this idea adds on some of the share page fields that describe share language to other actions like petitions, events, etc..., allowing that data to be pulled from the API. 

One expected use case is folks building their own thank you pages for petitions instead of using our built-in ones, so admins can still use our UI to manage the action and share language, but that data can be pulled over the API and after signing users can be redirected to a custom share page with that language pulled from the API.

**Comment by joshco** [comment]
Kyle, will you be on tomorrow's call?  If so, we can have a discussion about this

**Comment by kyle-rader** [comment]
@j-ro Thank you for the description and context!

@joshco,  @amiel and I have a team meeting conflict with tomorrow's meeting so we will not be on the call.  I'm interested in learning more about this more and will try to join next week if that meeting is still on.

**Comment by joshco** [comment]
unfortunately, Jason will be on vacation next week.  Is it possible for you to juggle and attend tomorrow?  we can agenda this as first thing on the call, so you'd only need to attend for as long as the discussion takes.

**Comment by kyle-rader** [comment]
@joshco Unfortunately it's a planned company wide meeting, we've reserved the entire day day for so no juggling.  No worries, I will try to get in and read up on this specification and those relating to see how Action Sprout can contribute in the future.

**Comment by joshco** [comment]
okiedoke

**Comment by amiel** [comment]
This looks great!

**Pull request merged**
