### PR TITLE
feat(triggers): adds types of autoresponders

### PR DESCRIPTION
**Pull request by robertsonsamuel**
Pull request for enhancement for different types of autoresponders via #292.

### CODE REVIEW

**Comment by j-ro** [comment]
This looks good! I'd say we may need a bit more explanation on what identifiers are in this case, since they're a bit different from our normal ones. Basically just saying this identifies a specific autoresponse on the server, and how those identifiers are constructed is server behavior rather than spec, since autoresponses aren't their own API resources.

We also probably want to add this partial to the person signup helper too.

**Comment by robertsonsamuel** [comment]
Makes sense, I'll get a pull request with those changes. 👍

**Comment by robertsonsamuel** [comment]
This is already on the person signup helper ? Do you mean include this partial on the People resource ?

**Comment by j-ro** [comment]
Ah, it is indeed, my mistake, no need to add then, just the update to wording.

**Comment by robertsonsamuel** [comment]
Perfect. Thank you!

**Comment by joshco** [comment]
Approved by committee 8/31

**Pull request merged**
