### PR TITLE
Fix docs for Record Canvass Helper re "target" indication

### PR DESCRIPTION
**Pull request by shaisachs**
As discussed on our call 5 Nov.

### CODE REVIEW

**Comment by j-ro** [comment]
I don't understand this -- you post to the record canvass helper on a person object, so isn't target implied that way?

I think once we have canvass efforts or whatever we call them, the overarching canvass type like petitions, we'll need something like this, but now, as it stands, I think the person targeted is implied by the link you post to, no?

**Comment by shaisachs** [comment]
Yes, that's essentially what this hotfix is meant to fix.  Earlier it looked as though the target was included in the body.

**Comment by j-ro** [comment]
Oh, duh. I read my diffs backwards. Cool.

**Comment by joshco** [comment]
Should we also allow an inlined person like in other helpers for cases where the client doesnt yet have a route? (or vanid)

**Comment by j-ro** [comment]
As it's written now, no -- you must have a person first. When we get the canvass overarching object (the petition to the record signature helper, by way of analogy), then yes, if you were posting to /canvass_effort/[id]/canvass/ you'd inline a person. But here, since there is no overarching effort, you have to have the person first.

**Comment by joshco** [comment]
Approved by unanimous consent 11/12

**Pull request merged**
