### PR TITLE
Remove Chuck Hagenbuch

### PR DESCRIPTION
**Pull request by chuck**
I wish to be removed. I am also no longer at Blue State Digital.

### CODE REVIEW

**Comment by j-ro** [comment]
@mklaber as a rule, we discuss and approve PRs before merging them...

**Comment by mklaber** [comment]
@j-ro sorry, didn't think these were things that needed discussion. And, I can't speak for the formerly-BSD folks, but my removal was timely as hinted at in my comment 45837dc08efa33ad922eccd99a7cf615f1472166

@chuck I should have caught this when merging your PR but you gotta make it against the `gh-pages` branch to get it updated on the website. My commit powers were revoked while I was trying to repoint your PR.

**Comment by j-ro** [comment]
None of this is controversial, so I'm sure these can be merged in short order, but there's still a procedure here that should be followed.

**Comment by joshco** [comment]
@j-ro is correct.

**Comment by mklaber** [comment]
@joshco 
image

**Comment by j-ro** [comment]
Let's keep this focused on the work, folks.

**Pull request merged**
