### PR TITLE
Expand status page to include explicit data contracts around HTTP status...

### PR DESCRIPTION
**Pull request by shaisachs**
... codes and errors.  Clarify atomic and non-atomic request failure handling.

Signed-off-by: shaisachs <ssachs@ngpvan.com>

### CODE REVIEW

**Comment by shaisachs** [comment]
Whoops, hit enter too quickly.  In any case, my promised PR on status codes and validation errors.  Here's an overview:

* Explicitly embraces using HTTP response codes to indicate the type of success/failure of a request
* Provides a model for developer-friendly validation errors
* Clarified approach to handling failure of non-atomic requests (e.g. person signup helper.)

By intention, I haven't gone through and made global changes to response codes for existing resources; for ex. if we follow this PR then every successful DELETE should respond with 204, but most of the docs specify 200.  My thinking is basically I'd like to get feedback on that change before doing a ton of find-and-replace.  That said, I do want to be up-front that the changes proposed for HTTP status codes are somewhat sweeping.

**Comment by joshco** [comment]
Last night I updated the status.md page to the new format.
Can you merge in those changes and update your pull request?

**Comment by shaisachs** [comment]
Sure thing, I just did that.  Sorry I missed it earlier.

I specifically wanted, in this PR, to address the issue of atomicity/non-atomicity, since that seemed to be the idea behind the "trace" stuff in the original draft, but I thought the original draft could use more clarity.

If you like I can certainly add back the simple Tagging example you provided in last night's update, though in my view it should be a simple 405, and a 500 should be reserved for things like database errors or other exceptional conditions.

**Comment by j-ro** [comment]
quick read, looking pretty good to me!

**Comment by joshco** [comment]
I like it too.  A few comments

__Multiple-Errors__
When returning multiple errors, I think having a main error object with a sub-error object of some sort is simpler for the client.  When this type of format, the client error processing is simpler.  It can go to a known location in the json document for the top level error code and ignore the sub-errors if it wants.  
Error processing should be as simple as possible.  (When you are in an error situation, more complexity is the last thing you need)

Right now, the client must first detect if it is looking at an array or single object.  Then it must decide what error to pay attention to.  
That's what the trace was about.

**Comment by shaisachs** [comment]
Fair enough.  I reorganized the page a fair amount, but I think the result is quite a lot nicer.  If you look at the examples at the end, you'll see that response bodies for atomic and non-atomic failures are essentially the same, except in the ways you'd expect them to be different.

**Comment by shaisachs** [comment]
I've just now incorporated Josh's suggestion from the call, WRT reporting back the successfully created resource in the non-atomic scenario.  I named the resource osdi:error rather than :status simply for expedience - because I didn't want to have to change the file name and a bunch of headings in the document itself - but if it's a big deal to anyone we can certainly switch back to osdi:status.

**Comment by joshco** [comment]
approved 4/2
Motion to approve
Passed by unanimous consent

**Pull request merged**
