### PR TITLE
Make record canvass helper discoverable

### PR DESCRIPTION
**Pull request by shaisachs**
Turns out there was no way to discover the record canvass helper!  This PR fixes that.  Assuming we are good with this approach, we probably want to do the same for record attendance helper, record donation helper, etc., but I wanted to start with this so I can get our Record Canvass Helper implementation going.

### CODE REVIEW

**Comment by j-ro** [comment]
This looks like the right place for it to me. Though I think it should be `record_canvass_helper` to keep with our others.

The others are in fact discoverable, they're on their respective action endpoints, like here:

https://github.com/opensupporter/osdi-docs/blob/gh-pages/petitions.md#scenario-retrieving-a-collection-of-petition-resources-get

So, when the canvass efforts spec is done, I'd suspect this link goes there too.

**Comment by shaisachs** [comment]
Fair enough.  Latest commit should conform to those standards.

**Comment by shaisachs** [comment]
Assuming this gets merged next Thursday, it should trigger a new sub-minor version number (1.0.3 I think) - should I do that before the merge or after?

**Comment by j-ro** [comment]
I'd say part of this pr?



_________________________________
Jason Rosenbaum

Email/GChat: seminal@theseminal.com
Cell: 914.806.1939
Twitter: http://twitter.com/j_ro

**Comment by shaisachs** [comment]
Ok sounds good.

**Pull request merged**
